export const mockEvents = [
  {
    id: "1",
    title: "Tech Innovation Summit 2025",
    date: "2025-12-15",
    location: "San Francisco Convention Center, CA",
    category: "conference",
    description:
      "Join industry leaders and innovators for a day of inspiring talks, networking, and exploring the future of technology. Featuring keynotes from Fortune 500 CEOs and interactive workshops.",
    attendees: 450,
    capacity: 500,
    image: "/tech-conference-hall-with-stage.jpg",
    organizer: "TechEvents Inc.",
  },
  {
    id: "2",
    title: "Summer Music Festival",
    date: "2025-07-20",
    location: "Central Park, New York",
    category: "concert",
    description:
      "Experience an unforgettable evening of live music with performances from top artists. Food, drinks, and entertainment throughout the night.",
    attendees: 2500,
    capacity: 3000,
    image: "/outdoor-concert-stage-with-lights.jpg",
    organizer: "Live Events Co.",
  },
  {
    id: "3",
    title: "Digital Marketing Workshop",
    date: "2025-12-08",
    location: "Downtown Office Hub, Chicago",
    category: "workshop",
    description:
      "Learn the latest digital marketing strategies and tools from industry experts. Hands-on sessions covering SEO, social media, and analytics.",
    attendees: 85,
    capacity: 100,
    image: "/workshop-classroom-with-people-learning.jpg",
    organizer: "Marketing Academy",
  },
  {
    id: "4",
    title: "Web Developers Meetup",
    date: "2025-12-10",
    location: "Tech Hub Downtown, Austin",
    category: "meetup",
    description:
      "Monthly gathering of web developers. Share projects, discuss technologies, and network with fellow developers in your area.",
    attendees: 120,
    capacity: 150,
    image: "/developers-networking-event.jpg",
    organizer: "Austin Dev Community",
  },
  {
    id: "5",
    title: "City Marathon 2025",
    date: "2025-11-02",
    location: "Downtown Starting Point, Boston",
    category: "sports",
    description:
      "Join thousands of runners for the annual city marathon. 5K, 10K, and full marathon options available. Registration includes t-shirt and refreshments.",
    attendees: 1800,
    capacity: 2000,
    image: "/city-marathon.png",
    organizer: "Boston Marathon Committee",
  },
  {
    id: "6",
    title: "Business Networking Breakfast",
    date: "2025-12-12",
    location: "Premium Hotel Downtown, Seattle",
    category: "conference",
    description:
      "Start your day with valuable connections. Network with successful entrepreneurs and business leaders over breakfast and coffee.",
    attendees: 75,
    capacity: 80,
    image: "/business-networking-event-in-hotel.jpg",
    organizer: "Seattle Business Network",
  },
  {
    id: "7",
    title: "Jazz Night",
    date: "2025-11-15",
    location: "Blue Note Jazz Club, New York",
    category: "concert",
    description:
      "An intimate evening of live jazz performances. Enjoy world-class musicians, fine dining, and a sophisticated atmosphere.",
    attendees: 280,
    capacity: 300,
    image: "/jazz-musician-performing-in-club.jpg",
    organizer: "Jazz Culture Foundation",
  },
  {
    id: "8",
    title: "AI & Machine Learning Workshop",
    date: "2025-12-18",
    location: "Innovation Center, San Jose",
    category: "workshop",
    description:
      "Deep dive into AI and ML technologies. Learn practical applications, tools, and best practices from industry experts.",
    attendees: 160,
    capacity: 200,
    image: "/ai-machine-learning-workshop-presentation.jpg",
    organizer: "Tech Learning Institute",
  },
  {
    id: "9",
    title: "Startup Pitch Night",
    date: "2025-12-05",
    location: "Venture Capital Hub, Palo Alto",
    category: "meetup",
    description:
      "Watch ambitious startups pitch their ideas to investors. Network with founders, VCs, and entrepreneurs.",
    attendees: 200,
    capacity: 250,
    image: "/startup-pitch-event-presentation.jpg",
    organizer: "Silicon Valley Ventures",
  },
  {
    id: "10",
    title: "Basketball Championship",
    date: "2025-11-25",
    location: "Sports Arena, Los Angeles",
    category: "sports",
    description:
      "The most anticipated basketball game of the season. Premium seating available. Gates open 2 hours before game time.",
    attendees: 15000,
    capacity: 18000,
    image: "/basketball-arena-championship-game.jpg",
    organizer: "Professional Sports League",
  },
]
